---
- name: configure virtual hosts
  template: src=wp.conf.j2 dest=/etc/httpd/conf.d/wp.conf owner=root group=root

- name: remove default apache site
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- name: restart apache
  service: name=httpd state=restarted enabled=yes
