---
- name: set directory permissions of {{ project_dir }}
  file: path={{ project_dir }} state=directory \
        owner={{ deploy_user }} group={{ deploy_group }} recurse=yes mode=2770

- name: set file permissions of {{ project_dir }}
  command: find {{ project_dir }} -type f -exec chmod 664 {} \;

- selinux: policy=targeted state=enforcing

- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes

- name: update ssh config
  copy: src=sshd_config dest=/etc/ssh/sshd_config \
        owner=root group=root mode=0400
  notify:
  - restart sshd

- meta: flush_handlers
