---
- name: check for existing WordPress installation
  stat: path={{ project_dir }}/wp-content
  register: wp_content

- include: install.yml
  when: wp_content.stat.exists == False

- include: plugins.yml
